# Generated by Django 4.1.7 on 2023-03-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_location_user_locations_alter_user_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='locations',
            new_name='location',
        ),
    ]
