# Generated by Django 4.1.7 on 2023-02-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ad',
            new_name='Ads',
        ),
    ]
