# Generated by Django 4.1.7 on 2023-02-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_remove_ads_author_ads_author_id_ads_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
