# Generated by Django 4.1.7 on 2023-02-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ads_options_alter_ads_address_alter_ads_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='address',
        ),
    ]
