# Generated by Django 4.1.7 on 2023-02-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_remove_ads_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='image',
        ),
    ]
